# Generated by Django 3.1.2 on 2020-10-31 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCar', '0003_misionyvision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('ident', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(null=True, upload_to='car')),
            ],
        ),
    ]
