# Generated by Django 3.1.2 on 2020-10-31 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCar', '0004_galeria'),
    ]

    operations = [
        migrations.AddField(
            model_name='misionyvision',
            name='numero',
            field=models.IntegerField(default=1),
        ),
    ]
