# Generated by Django 3.1.2 on 2020-10-31 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myCar', '0005_misionyvision_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='misionyvision',
            name='numero',
        ),
    ]
